// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0emhyFFwcMuBwCdc73h7zNuuraBOFIy0',
    appId: '1:671880481063:web:18a4e6f6dce9aed1744102',
    messagingSenderId: '671880481063',
    projectId: 'newtask-d4193',
    authDomain: 'newtask-d4193.firebaseapp.com',
    storageBucket: 'newtask-d4193.appspot.com',
    measurementId: 'G-8KW5VMLL7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCN78yH7VhevypFq0jj6ojOrmfaYbB0w',
    appId: '1:671880481063:android:c1772acdb366e247744102',
    messagingSenderId: '671880481063',
    projectId: 'newtask-d4193',
    storageBucket: 'newtask-d4193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUy6gS99HdiKWbwDvgT6QOgELx9DhEx08',
    appId: '1:671880481063:ios:ce3d0fdb65d00fa8744102',
    messagingSenderId: '671880481063',
    projectId: 'newtask-d4193',
    storageBucket: 'newtask-d4193.appspot.com',
    iosBundleId: 'com.worksdelight.worksDelight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUy6gS99HdiKWbwDvgT6QOgELx9DhEx08',
    appId: '1:671880481063:ios:ce3d0fdb65d00fa8744102',
    messagingSenderId: '671880481063',
    projectId: 'newtask-d4193',
    storageBucket: 'newtask-d4193.appspot.com',
    iosBundleId: 'com.worksdelight.worksDelight',
  );
}
